### ISSUE TITLE
Unable to initialize Enum from int

### ISSUE THREAD

**Issue by CubeMD** [MHDante/pythonnet-stub-generator#1]
Enums seem to be abstract, which prevents initialization from integers

![image](https://user-images.githubusercontent.com/5870779/218887523-5b1958c2-f1f2-434e-a8a6-0f6cb94a78b1.png)

**Comment by MHDante** [comment]
Solved in [1.2.1](https://github.com/MHDante/pythonnet-stub-generator/releases/tag/1.2.1)
